services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: next-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    volumes:
      - ./public:/app/public
      - ./.next:/app/.next
    networks:
      - app-network

networks:
  app-network:
    driver: bridge